### ISSUE TITLE
Please, upload cstrike15/cs_gamerules I would like to take a look, thanks.

### ISSUE THREAD

**Issue by martinjanas** [perilouswithadollarsign/cstrike15_src#1]

**Comment by moooooi** [comment]
while this repo is down
[here](https://github.com/transseksuaali/cstrike15_src/tree/master/game/shared/cstrike15)

edit: seems like the repo is back up now

**Comment by perilouswithadollarsign** [comment]
thank you @transseksuaali, as you said the full repo has been reuploaded
