### ISSUE TITLE
This might help idk

### ISSUE THREAD

**Issue by youssef02** [perilouswithadollarsign/cstrike15_src#11]
https://developer.valvesoftware.com/wiki/Valve_Project_Creator

vpc commands:

VPC - Valve Project Creator For Visual Studio, Xbox 360, PlayStation 3, Xcode and Make (Build: Aug 27 2014 12:55:48)
(C) Copyright 1996-2010, Valve Corporation, All rights reserved.

Source Path: D:\Games\Steam\SteamApps\sourcemods\assets\code-2013
Target Platform: win32
Generating for Visual Studio 2013.

usage: vpc [options] <+/-/*project or group>

Examples:

  Single .vcproj generation:
    vpc +client /hl2     <-- Creates a Win32 .vcproj for the HL2 client.
    vpc +shaderapi /x360 <-- Creates a Xbox360 .vcproj for the shaderapi.

  Multiple .vcproj generation - Multiple Projects for Games and Platforms:
    vpc +client /hl2 /tf           <-- Creates ALL the Win32 .vcprojs for the HL2 and TF client.
    vpc +gamedlls /allgames        <-- Creates ALL the Win32 .vcprojs for client and server for all GAMES.
    vpc +tools -tier0 /win32 /x360 <-- Creates ALL the Win32 and Xbox360 .vcprojs for the tool projects but not the tier0 project.

  Use +/- to add or remove projects or groups.
  Use *   to add a project and all projects that depend on it.
  Use @   to add a project and all projects that it depends on.
  Use /h spew final target build set only (no .vcproj created).

  Further details can be found on Valve Internal Wiki on VPC.

--- OPTIONS ---
[/q]:          Quiet mode (quiet mode is automatically on if the VPC_QUIET environment variable is set)
[/v]:          Verbose
[/f]:          Force generate .vcproj, otherwise use crc checks
[/dp]:         Decorate project names with platform
[/testmode]:   Override output .vcproj file to be named 'test.vcproj'
[/srcctl]:     Enable source control integration
[/2013]:       Generate projects and solutions for Visual Studio 2013 [default]
[/2012]:       Generate projects and solutions for Visual Studio 2012
[/2010]:       Generate projects and solutions for Visual Studio 2010
[/2005]:       Generate projects and solutions for Visual Studio 2005
[/nounity]:    Disable unity file generation

--- Help ---
[/h]:          Help
[/?]:          Help
[/platforms]:  Spew Platforms
[/games]:      Spew Games
[/projects]:   Spew Projects
[/groups]:     Spew Groups
[/properties]: Spew VS2005 Properties

--- Conditionals ---
[/profile]:    Set Reserved $PROFILE=1
[/retail]:     Set Reserved $RETAIL=1
[/callcap]:    Set Reserved $CALLCAP=1
[/fastcap]:    Set Reserved $FASTCAP=1
[/nofpo]:      Set Reserved $NOFPO=1
[/lv]:         Set Reserved $LV=1
[/demo]:       Set Reserved $DEMO=1
[/no_steam]:   Set Reserved $NO_STEAM=1
[/qtdebug]:    Set Reserved $QTDEBUG=1
[/no_ceg]:     Set Reserved $NO_CEG=1
[/upload_ceg]: Set Reserved $UPLOAD_CEG=1

--- Other ---
[/mksln]:      <.sln filename> - make a solution file
[/p4sln]:      <.sln filename> <changelists...> - make a solution file based on
               the changelist. Changelists can be specific numbers, 0 or "default"
               for the default changelist, or "all" for all active changelists.
[/nop4add]:    Don't automatically add project files to Perforce
[/slnitems]:   <filename> - adds all files listed in <filename> to generated
               solutions
[/showdeps]:   Show an example dependency chain for each project that depends
               on your p4 change list(s).  Use with /p4sln.
[/checkfiles]: Check for the existence of files in $file commands. For debugging vpc files.
               Only works if the currrent directory is the project directory.
[/define:xxx]: Enable a custom conditional $XXX to use for quick testing in VPC files.

**Comment by Titaniumtown** [comment]
it keeps complaining that it's missing files

**Comment by youssef02** [comment]
Can you post your error here? What files

**Comment by youssef02** [comment]
> it keeps complaining that it's missing files

What files?

**Comment by Titaniumtown** [comment]
i can't remember atm, stuff that's in the source sdk, but idk how to install the source sdk (im on linux)

**Comment by Titaniumtown** [comment]
I also think i need those depot files, I made an issue requesting a torrent of them.

**Comment by Titaniumtown** [comment]
I also may be stupid

**Comment by Titaniumtown** [comment]
Do you have access to the depot files? If so, could you make a github repo or make a torrent?

**Comment by youssef02** [comment]
> I also may be stupid

Well i am no expert but i just keep googeling stuff

**Comment by Titaniumtown** [comment]
me too

**Comment by Titaniumtown** [comment]
do you have the depot files? could you make a zip or something? I can create a torrent

**Comment by youssef02** [comment]
Sorry idk i got myversion from unknowncheat where it got leaked

**Comment by Titaniumtown** [comment]
what does that mean?

**Comment by youssef02** [comment]
What do you mean?

**Comment by Titaniumtown** [comment]
oh nvm, im an idiot. I read your sentence weird.

**Comment by Titaniumtown** [comment]
im just going to boot up my windows 10 kvm. I will make a torrent shortly

**Comment by Titaniumtown** [comment]
it'll take a little while longer, i have to install visual studio.

**Comment by youssef02** [comment]
Take your time i have a Ramadan to prepare for.

**Comment by Titaniumtown** [comment]
k

**Comment by Titaniumtown** [comment]
btw I found a link on 4chan of someone who said they got it to compile:
[Link](https://boards.4channel.org/v/thread/504872574/i-got-it-to-build-heres-how)

**Comment by Titaniumtown** [comment]
oh wait, I can just install the dotnet and dotnet-sdk packages on arch, lol

**Comment by Titaniumtown** [comment]
downloading now :)

**Comment by Titaniumtown** [comment]
holy crap, it's like 13.9 gb for just the windows version.

**Comment by Titaniumtown** [comment]
im creating the torrent now. It's huge, like 30 gb

**Comment by Titaniumtown** [comment]
[csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4532237/csgo_depots.zip)

unzip it and there will be a .torrent file, enjoy

**Comment by Titaniumtown** [comment]
first time creating a torrent :)

**Comment by Headcrabed** [comment]
> 
> 
> [csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4532237/csgo_depots.zip)
> 
> unzip it and there will be a .torrent file, enjoy

Thanks.

**Comment by Titaniumtown** [comment]
:)

**Comment by Titaniumtown** [comment]
START SEEDING

**Comment by Titaniumtown** [comment]
distribute the torrent!

**Comment by Titaniumtown** [comment]
wait, i think i screwed up
how do you add trackers?

**Comment by Titaniumtown** [comment]
oh crap

**Comment by Titaniumtown** [comment]
@Headcrabed I made a mistake, a new torrent file will be available shortly.

**Comment by Titaniumtown** [comment]
[csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4532264/csgo_depots.zip)

**Comment by Titaniumtown** [comment]
there we are

**Comment by Titaniumtown** [comment]
i think that should work, i am new to creating torrents.

**Comment by Titaniumtown** [comment]
Tell me if it doesn't :)

**Comment by bxff** [comment]
@youssef02 @Titaniumtown  btw, what about the files that have `/** Removed for partner depot **/`  found in some parts of the code?

**Comment by Tushar1337** [comment]
Can i use this source code to know what is inside a csgo case? xD

**Comment by Titaniumtown** [comment]
@Tushar1337 no

**Comment by perilouswithadollarsign** [comment]
thanks for the torrent @Titaniumtown, @Tushar1337 read the readme
