### ISSUE TITLE
depots

### ISSUE THREAD

**Issue by Kentavrik** [perilouswithadollarsign/cstrike15_src#13]
Hey guys! Anybody has depots for csgo (
731 7043469183016184477
732 4047004309608881181)
Because valve deleted them and i cant compile then

**Comment by Kentavrik** [comment]
and has anybody solution for this error ERROR: Unable to find RegKey for .vcxproj files in solutions.
when i run CreateSolution.bat

**Comment by JusicP** [comment]
> and has anybody solution for this error ERROR: Unable to find RegKey for .vcxproj files in solutions.
> when i run CreateSolution.bat

You need to download vs2015 to fix this error

**Comment by perilouswithadollarsign** [comment]
@Kentavrik  @JusicP should have answered your question
