### ISSUE TITLE
csgo depot torrent

### ISSUE THREAD

**Issue by Titaniumtown** [perilouswithadollarsign/cstrike15_src#14]
As I am still new to creating torrents, I realized I screwed up again with the torrent for the depots. I will link another one in this issue soon.

**Comment by Titaniumtown** [comment]
Can someone test the torrent bellow? You need to unzip the zip file to get the torrent file.

[csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4548972/csgo_depots.zip)

**Comment by Titaniumtown** [comment]
If that doesn't work, I have another idea. Could someone PLEASE test it? I want to be able to have a good torrent.

**Comment by Titaniumtown** [comment]
[csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4549260/csgo_depots.zip)
This should work

**Comment by Titaniumtown** [comment]
I can't get the torrenting to work, ughhhh

**Comment by Titaniumtown** [comment]
I've tried everything

**Comment by Titaniumtown** [comment]
I'm not even getting an error or anything. Just:
Seeds: 0 (5)
Peers: 0 (1)

anyone know the issue???

**Comment by Titaniumtown** [comment]
wait, i think it's working now!

**Comment by Titaniumtown** [comment]
oh btw, here's the working torrent!
[csgo_depots.zip](https://github.com/perilouswithadollarsign/cstrike15_src/files/4562897/csgo_depots.zip)

**Comment by Titaniumtown** [comment]
don't use the previous ones

**Comment by rongcto** [comment]
thx lot ,i can wait.no speed.
![Snipaste_2020-05-02_10-28-57](https://user-images.githubusercontent.com/64672804/80853062-4aecbf80-8c60-11ea-8df4-7d76bf03952a.png)

**Comment by rongcto** [comment]
can u make csgo_depots to magnet link ? thx

**Comment by perilouswithadollarsign** [comment]
welp seems like u got it fixed
