### ISSUE TITLE
Magnet link

### ISSUE THREAD

**Issue by Titaniumtown** [perilouswithadollarsign/cstrike15_src#15]
Is anyone else having issues w/ the magnet link? I'm getting a "Tracker Status: Error: Permission Denied"

**Comment by Titaniumtown** [comment]
nvm

**Comment by cloudcloudskies** [comment]
i uploaded a version i made myself (i exported everything, removed unrequired stuff) to google drive, i can send it if you want

**Comment by cloudcloudskies** [comment]
and its 2.72 gb (7z)
