### ISSUE TITLE
Trojan.Win32.Krypt

### ISSUE THREAD

**Issue by deadfan** [perilouswithadollarsign/cstrike15_src#16]
Trojan.Win32.Krypt  LOL

**Comment by Titaniumtown** [comment]
Thanks for sharing.

**Comment by perilouswithadollarsign** [comment]
this is super old but thanks for nothing. if you read the read me like you were supposed to, youd see i didnt code this. this is a leak of (most of) the source code to the game. all i did was upload it to github
