### ISSUE TITLE
P2 source included?

### ISSUE THREAD

**Issue by conneath** [perilouswithadollarsign/cstrike15_src#18]
i see some portal-related files inside the game folder, does this mean this leak includes Portal 2 source too? or are they just leftovers

**Comment by notfrying1pans** [comment]
The leak contains a partial copy of the Portal 2 source code, which was collected over the course of several years and leaked in 2019. The leaker of this included them in it for some reason. You can find remnants of the collection throughout various folders which still have their zips intact.

**Comment by conneath** [comment]
thanks, i don't think i can compile P2 with this, but still helpful

**Comment by notfrying1pans** [comment]
You're welcome. All of the leaked portal 2 code is in here. I remember the leaker for this wanting to get a copy of the P2 leak back then.
