### ISSUE TITLE
How to compile this shit?

### ISSUE THREAD

**Issue by evgeny200633** [perilouswithadollarsign/cstrike15_src#19]
How to compile this shit?

**Comment by Titaniumtown** [comment]
you can't really.

**Comment by miifanboy** [comment]
actually you can I don't remember how but I could manage to do it a few months ago but the game becomes very unstable with lots of black textures fps drops and distorted sounds.

**Comment by VDeltaGabriel** [comment]
does someone know how to get socketlib.vpc? I have error that says "cannot open socketlib.vpc" and I don't know where to get it

**Comment by evgeny200633** [comment]
> does someone know how to get socketlib.vpc? I have error that says "cannot open socketlib.vpc" and I don't know where to get it

Are you trying to build "everything" group?
Many projects are missing from it and unbuildable, such as physics. When I tried to compile all this, from the "csgo_partner" group I got compilation errors of engine, client, server, matchmaking dlls.

If you want to play around with this, you can just comment out the missing projects in projects.vgc

**Comment by VDeltaGabriel** [comment]
I actually tried to do stuff with hl2_src since there's more stuff that I wanted

**Comment by evgeny200633** [comment]
> I actually tried to do stuff with hl2_src since there's more stuff that I wanted

hl2_src broken too(
It's compilable but have many bugs

**Comment by VDeltaGabriel** [comment]
Is SDKLauncher project possible to compile?
I wanted to make custom sdklauncher and hammer editor

**Comment by evgeny200633** [comment]
> Is SDKLauncher project possible to compile? I wanted to make custom sdklauncher and hammer editor

It seems to be possible, at least Hammer for sure. I can't say anything about SDKLauncher

**Comment by VDeltaGabriel** [comment]
Can you tell me how to compile it?
(What project or files do I need to setup to compile hammer editor)?

**Comment by kristiker** [comment]
https://github.com/SwagSoftware/Kisak-Strike

**Comment by jdoexbox360** [comment]
> actually you can I don't remember how but I could manage to do it a few months ago but the game becomes very unstable with lots of black textures fps drops and distorted sounds.

Did u use compiler optimisations lol. Btw I think I need to compile this "shit" with da makefile not just running a c file visual studio

**Comment by conneath** [comment]
last time i tried hl2_src i ran into problems with "binkw32.lib" which i assume is Bink, i found a copy of it in team-comtress2 but im pretty sure the lib is VS2015 only and i was too lazy to install it (i was using vs2013 tools)

**Comment by i1u5** [comment]
Gigachad

**Comment by jdoexbox360** [comment]
> How to compile this shit?

https://securitronlinux.com/battlefield/how-to-compile-the-leaked-csgo-source-code-leak-this-apparently-works/

**Comment by evgeny200633** [comment]
> > How to compile this shit?
> 
> https://securitronlinux.com/battlefield/how-to-compile-the-leaked-csgo-source-code-leak-this-apparently-works/
This compilation guide will not help due to the fact that several more actions need to be done.

I forgot to close this topic)
I've been able to build everything for a long time and the engine worked. The client and server dll code did not work for obvious reasons in the form of the lack of economy source.
The build was made for VS 2019, because build under VS 2015 is impossible.

**Comment by acnbhop** [comment]
Yo, could you tell me how? I'm using vs 2019 and it just launches with a black screen and closes almost instantly.

**Comment by IAhmadGT** [comment]
> > > How to compile this shit?
> > 
> > 
> > https://securitronlinux.com/battlefield/how-to-compile-the-leaked-csgo-source-code-leak-this-apparently-works/
> > This compilation guide will not help due to the fact that several more actions need to be done.
> 
> I forgot to close this topic) I've been able to build everything for a long time and the engine worked. The client and server dll code did not work for obvious reasons in the form of the lack of economy source. The build was made for VS 2019, because build under VS 2015 is impossible.

is it possible with VS 2022?

**Comment by evgeny200633** [comment]
> > > > How to compile this shit?
> > > 
> > > 
> > > https://securitronlinux.com/battlefield/how-to-compile-the-leaked-csgo-source-code-leak-this-apparently-works/
> > > This compilation guide will not help due to the fact that several more actions need to be done.
> > 
> > 
> > I forgot to close this topic) I've been able to build everything for a long time and the engine worked. The client and server dll code did not work for obvious reasons in the form of the lack of economy source. The build was made for VS 2019, because build under VS 2015 is impossible.
> 
> is it possible with VS 2022?

yeah

**Comment by vbsp-exe** [comment]
GUYS I GOT GOOD NEWS!

I found the socketlib.vpc!

**Comment by miifanboy** [comment]
> GUYS I GOT GOOD NEWS!
> 
> I found the socketlib.vpc!

WHEREE???

**Comment by vbsp-exe** [comment]
> > GUYS I GOT GOOD NEWS!
> > I found the socketlib.vpc!
> 
> WHEREE???

I had the file laying on my SSD.

**Comment by vbsp-exe** [comment]
![Image](https://github.com/user-attachments/assets/11ca221f-4624-4382-b5fb-fc283dd8afd8)
Very cool

**Comment by VDeltaGabriel** [comment]
please publish them

**Comment by vbsp-exe** [comment]
Ill make a new repository on my profile.

**Comment by vbsp-exe** [comment]
https://github.com/LambdaComplexSource/LambdaComplexSource, uploaded the socketlib.vpc file

```bash
src/socketlib/
```

**Comment by evgeny200633** [comment]
It's not quite the same) Look at src/public/socketlib.h, it's Valve implementation library, not third-party

**Comment by evgeny200633** [comment]
socketlib is a Source2 library that used for VConsole

**Comment by vbsp-exe** [comment]
It's the one on my disk, it has the same functions

**Comment by StripperPaws** [comment]
Question, sorry for deadposting. Do you still have socketlib.vpc? I have not been able to find it.

**Comment by IAhmadGT** [comment]
> Question, sorry for deadposting. Do you still have socketlib.vpc? I have not been able to find it.

Just comment it out in the everything vpc

**Comment by StripperPaws** [comment]
right, tyy. Did manage to source the lib though. we good :3

**Comment by Darkbyte-Studios** [comment]
Hey wsp, "vbsp.exe", I have no idea if you're still online but can you reupload the socketlib.vpc again?
