### ISSUE TITLE
Probably fake?

### ISSUE THREAD

**Issue by bxff** [perilouswithadollarsign/cstrike15_src#3]
Idk but I think the files on this repo is not complete, or fake?

the original like(I think):
https://archive.vn/VNno4

**Comment by Bluscream** [comment]
403 error?

**Comment by bxff** [comment]
What, the hole folder is like 5 gbs: 

magnet:?xt=urn:btih:21DDA6847DDE983F2F8063739249D2D1D09A5DDA&dn=April%2022nd%202020%2c%20random%20leaked%20shit.rar&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

**Comment by Titaniumtown** [comment]
*whole

**Comment by Titaniumtown** [comment]
It also has other leaks as well

**Comment by Titaniumtown** [comment]
https://www.reddit.com/r/tf2/comments/g6hsa5/taking_a_look_at_the_leaked_files/

**Comment by HowToDoThis** [comment]
this is a old leaked source code which is from a very long time ago at 2018, then someone just reposted only.

**Comment by perilouswithadollarsign** [comment]
This is not up to date source code, it can be updated and fixed to a certain extent but its more so to be used as a base to learn to make cheats or games from
