### ISSUE TITLE
DMCA incoming

### ISSUE THREAD

**Issue by lofcz** [perilouswithadollarsign/cstrike15_src#5]
backup this fast

**Comment by bxff** [comment]
It have already 100+ forks, I wonder if they would be removed too?

**Comment by Bluscream** [comment]
Yes, DMCA'ed repos automatically have all forks dmca'ed and the account suspended

**Comment by perilouswithadollarsign** [comment]
@lofcz @bin0x00 @Bluscream  how do you think i uploaded this? i have the folder as well as the magnet link and i can upload it over and over
