### ISSUE TITLE
can't even make a solution

### ISSUE THREAD

**Issue by maksw2** [perilouswithadollarsign/cstrike15_src#56]
Writing solution file C:\Users\Izabela\Desktop\MAKS\cstrike15_src\csgo_partner.sln.
ERROR: Unable to find RegKey for .vcxproj files in solutions.

**Comment by Bluscream** [comment]
Thats not a solution. Thats a workaround!

**Comment by maksw2** [comment]
very funny. so, it won't create a solution, and when i try to compile it, it compiles 0 files. _succesfully_.

**Comment by maksw2** [comment]
valve won't help. maybe you will.

**Comment by maksw2** [comment]
found it. https://github.com/ValveSoftware/source-sdk-2013/issues/72
