### ISSUE TITLE
How to compile (I'm on linux)

### ISSUE THREAD

**Issue by Titaniumtown** [perilouswithadollarsign/cstrike15_src#6]
btw i use arch

**Comment by Titaniumtown** [comment]
I do chmod +x ./devtools/bin/linux/* then ./devtools/bin/linux/vpc /csgo +csgo_partner /mksln csgo_partner.sln.
Then I get the error:
ERROR: Bad Syntax: [../vpc_scripts/source_base.vpc line:13 (or previous line)]

**Comment by Titaniumtown** [comment]
Ok, so when I use bash shell (i usually use fish bc it's better) it works. ending with 
Writing master makefile /home/simon/cstrike15_src/csgo_partner.mak.

But now i have no idea how to compile a binary.

**Comment by Titaniumtown** [comment]
ok, so a file called "csgo_partner.mak" is produced which you can put into the make command by running `make -f csgo_partner.mak` but now I have to edit compiler options like gcc and stuff

**Comment by HowToDoThis** [comment]
not very sure about how to build on windows other platform, since they built-in project files generator about every project

**Comment by Titaniumtown** [comment]
I am working on a script, I got it working

**Comment by HowToDoThis** [comment]
why don't you use VS :D its better for viewing, generating project files with any code about sourcesdk

**Comment by Titaniumtown** [comment]
I am having issues compiling, while I try again, I was just thinking, would the community be able to port csgo to other devices and architectures? like raspberry pi.

**Comment by perilouswithadollarsign** [comment]
@Titaniumtown if you can run a windows vm i recommend you use visual studio basic/code, its much more efficient and user-friendly. as i mentioned in a previous issue this is not up to date source, it can be updated to a certain extent but csgo is updated quite frequently so it wont ever be fully up to date unless another leak happens, which i highly doubt will ever come
