### ISSUE TITLE
Can it compile in windows (need help)

### ISSUE THREAD

**Issue by kaoti** [perilouswithadollarsign/cstrike15_src#7]
Well, i cant compile it, i tried to bulk compile all solutions and 48 of them was incorrect, im using VS2017, also i have vs2015, any idea?

Btw i have shit ton of errors (539 errors)

**Comment by kaoti** [comment]
Fail, more than 9000 errors, fuck me sideways

**Comment by 0xl0cal** [comment]
you download depots?

**Comment by kaoti** [comment]
Yep, but i dont have know where i need to put them.

**Comment by missing233** [comment]
I compiled them, but I couldn't play normally. The econ system does not work.

**Comment by HowToDoThis** [comment]
Just use what you want, current confirmed engine, engine_ds are buildable, you just need recompile files from dump

**Comment by HowToDoThis** [comment]
but engine has missing apart of the Econ System, which causes weapon not working at all

**Comment by kaoti** [comment]
Dont really care about playing, i only need it to try some weird stuff that ive been wanting to do since i saw the game.

**Comment by HowToDoThis** [comment]
me too, just interested about how they working :D

**Comment by kaoti** [comment]
Right!!!1

**Comment by HowToDoThis** [comment]
btw, there has another leaked code which is TF2, i think someone will upload soon. but who cares XD

**Comment by kaoti** [comment]
i dont need TF2 xD i dont play that game, i spend my time programming and playing csgo, lol

**Comment by perilouswithadollarsign** [comment]
@kaoti @HowToDoThis @miss1ng  a quote from another issue: "this is not up to date source, it can be updated to a certain extent but csgo is updated quite frequently so it wont ever be fully up to date unless another leak happens, which i highly doubt will ever come". do not expect this to be fully working. this isnt uploaded for people to paste the game everywhere, its to learn from.
